-- Seed data for Program/Schedule and Countries
-- Water Conference 2026

-- ============================================
-- PROGRAM DAYS
-- ============================================

-- Clear existing data first
DELETE FROM program_events;
DELETE FROM program_days;

INSERT OR IGNORE INTO program_days (day_number, date, title_ru, title_en, title_tj, short_title_ru, short_title_en, short_title_tj) VALUES
(1, '2026-05-25', 'День 1: Церемония открытия', 'Day 1: Opening Ceremony', 'Рӯзи 1: Маросими кушоиш', 'Церемония открытия', 'Opening Ceremony', 'Маросими кушоиш'),
(2, '2026-05-26', 'День 2: Тематические сессии', 'Day 2: Thematic Sessions', 'Рӯзи 2: Сессияҳои мавзӯӣ', 'Тематические сессии', 'Thematic Sessions', 'Сессияҳои мавзӯӣ'),
(3, '2026-05-27', 'День 3: Интерактивные диалоги', 'Day 3: Interactive Dialogues', 'Рӯзи 3: Гуфтугӯҳои интерактивӣ', 'Интерактивные диалоги', 'Interactive Dialogues', 'Гуфтугӯҳои интерактивӣ'),
(4, '2026-05-28', 'День 4: Церемония закрытия', 'Day 4: Closing Ceremony', 'Рӯзи 4: Маросими хотима', 'Церемония закрытия', 'Closing Ceremony', 'Маросими хотима');

-- ============================================
-- PROGRAM EVENTS - DAY 1
-- ============================================

INSERT OR IGNORE INTO program_events (day_id, event_type, time_start, time_end, title_ru, title_en, title_tj, description_ru, description_en, description_tj, location_ru, location_en, location_tj, sort_order) VALUES
(
    (SELECT id FROM program_days WHERE day_number = 1),
    'registration',
    '08:30', '10:00',
    'Регистрация участников',
    'Participant Registration',
    'Бақайдгирии иштироккунандагон',
    'Выдача бейджей и материалов конференции',
    'Badge and conference materials distribution',
    'Додани беҷҳо ва маводҳои конфронс',
    'Фойе главного зала',
    'Main Hall Lobby',
    'Фойеи толори асосӣ',
    1
),
(
    (SELECT id FROM program_days WHERE day_number = 1),
    'ceremony',
    '10:00', '11:30',
    'Торжественное открытие',
    'Grand Opening',
    'Кушоиши тантанавӣ',
    'Приветственные речи глав делегаций',
    'Welcome speeches by heads of delegations',
    'Суханрониҳои хайрамақдамии сарони ҳайатҳо',
    'Главный зал',
    'Main Hall',
    'Толори асосӣ',
    2
),
(
    (SELECT id FROM program_days WHERE day_number = 1),
    'break',
    '11:30', '12:00',
    'Кофе-брейк',
    'Coffee Break',
    'Танаффуси қаҳва',
    NULL, NULL, NULL,
    'Фойе',
    'Foyer',
    'Фойе',
    3
),
(
    (SELECT id FROM program_days WHERE day_number = 1),
    'plenary',
    '12:00', '13:30',
    'Пленарное заседание высокого уровня',
    'High-Level Plenary Session',
    'Ҷаласаи пленарии сатҳи баланд',
    'Доклады министров и представителей международных организаций',
    'Reports by ministers and representatives of international organizations',
    'Гузоришҳои вазирон ва намояндагони ташкилотҳои байналмилалӣ',
    'Главный зал',
    'Main Hall',
    'Толори асосӣ',
    4
),
(
    (SELECT id FROM program_days WHERE day_number = 1),
    'break',
    '13:30', '15:00',
    'Обед',
    'Lunch',
    'Хӯроки нисфирӯзӣ',
    NULL, NULL, NULL,
    'Банкетный зал',
    'Banquet Hall',
    'Толори банкет',
    5
),
(
    (SELECT id FROM program_days WHERE day_number = 1),
    'plenary',
    '15:00', '18:00',
    'Пленарное заседание (продолжение)',
    'Plenary Session (continued)',
    'Ҷаласаи пленарӣ (идома)',
    'Выступления делегаций стран-участниц',
    'Speeches by delegations of participating countries',
    'Суханрониҳои ҳайатҳои кишварҳои иштироккунанда',
    'Главный зал',
    'Main Hall',
    'Толори асосӣ',
    6
);

-- ============================================
-- PROGRAM EVENTS - DAY 2
-- ============================================

INSERT OR IGNORE INTO program_events (day_id, event_type, time_start, time_end, title_ru, title_en, title_tj, description_ru, description_en, description_tj, location_ru, location_en, location_tj, sort_order) VALUES
(
    (SELECT id FROM program_days WHERE day_number = 2),
    'session',
    '09:00', '10:30',
    'Сессия: Управление водными ресурсами',
    'Session: Water Resource Management',
    'Сессия: Идоракунии захираҳои обӣ',
    'Лучшие практики интегрированного управления водными ресурсами',
    'Best practices in integrated water resource management',
    'Беҳтарин таҷрибаҳо дар идоракунии ягонаи захираҳои обӣ',
    'Зал A',
    'Hall A',
    'Толори A',
    1
),
(
    (SELECT id FROM program_days WHERE day_number = 2),
    'break',
    '10:30', '11:00',
    'Кофе-брейк',
    'Coffee Break',
    'Танаффуси қаҳва',
    NULL, NULL, NULL,
    'Фойе',
    'Foyer',
    'Фойе',
    2
),
(
    (SELECT id FROM program_days WHERE day_number = 2),
    'session',
    '11:00', '12:30',
    'Сессия: Климат и водная безопасность',
    'Session: Climate and Water Security',
    'Сессия: Иқлим ва амнияти обӣ',
    'Адаптация к изменению климата в водном секторе',
    'Climate change adaptation in the water sector',
    'Мутобиқшавӣ ба тағйирёбии иқлим дар соҳаи об',
    'Зал B',
    'Hall B',
    'Толори B',
    3
),
(
    (SELECT id FROM program_days WHERE day_number = 2),
    'break',
    '12:30', '14:00',
    'Обед',
    'Lunch',
    'Хӯроки нисфирӯзӣ',
    NULL, NULL, NULL,
    'Банкетный зал',
    'Banquet Hall',
    'Толори банкет',
    4
),
(
    (SELECT id FROM program_days WHERE day_number = 2),
    'session',
    '14:00', '15:30',
    'Сессия: Трансграничное сотрудничество',
    'Session: Transboundary Cooperation',
    'Сессия: Ҳамкории марзгузар',
    'Опыт совместного управления водными ресурсами',
    'Experience in joint water resource management',
    'Таҷрибаи идоракунии муштараки захираҳои обӣ',
    'Зал A',
    'Hall A',
    'Толори A',
    5
),
(
    (SELECT id FROM program_days WHERE day_number = 2),
    'session',
    '15:30', '17:00',
    'Сессия: Инновации в водной отрасли',
    'Session: Innovation in the Water Sector',
    'Сессия: Навовариҳо дар соҳаи об',
    'Технологические решения для устойчивого водопользования',
    'Technological solutions for sustainable water use',
    'Ҳалҳои технологӣ барои истифодаи устувори об',
    'Зал B',
    'Hall B',
    'Толори B',
    6
);

-- ============================================
-- PROGRAM EVENTS - DAY 3
-- ============================================

INSERT OR IGNORE INTO program_events (day_id, event_type, time_start, time_end, title_ru, title_en, title_tj, description_ru, description_en, description_tj, location_ru, location_en, location_tj, sort_order) VALUES
(
    (SELECT id FROM program_days WHERE day_number = 3),
    'session',
    '09:00', '11:00',
    'Многосторонний диалог',
    'Multilateral Dialogue',
    'Гуфтугӯи бисёрҷонибӣ',
    'Обсуждение путей достижения ЦУР 6',
    'Discussion on achieving SDG 6',
    'Муҳокимаи роҳҳои ноилшавӣ ба ҲРУ 6',
    'Главный зал',
    'Main Hall',
    'Толори асосӣ',
    1
),
(
    (SELECT id FROM program_days WHERE day_number = 3),
    'break',
    '11:00', '11:30',
    'Кофе-брейк',
    'Coffee Break',
    'Танаффуси қаҳва',
    NULL, NULL, NULL,
    'Фойе',
    'Foyer',
    'Фойе',
    2
),
(
    (SELECT id FROM program_days WHERE day_number = 3),
    'session',
    '11:30', '13:00',
    'Презентации инновационных решений',
    'Innovative Solutions Presentations',
    'Презентатсияҳои ҳалҳои навоварона',
    'Демонстрация передовых технологий',
    'Demonstration of advanced technologies',
    'Намоиши технологияҳои пешқадам',
    'Выставочный зал',
    'Exhibition Hall',
    'Толори намоишгоҳ',
    3
),
(
    (SELECT id FROM program_days WHERE day_number = 3),
    'break',
    '13:00', '14:30',
    'Обед',
    'Lunch',
    'Хӯроки нисфирӯзӣ',
    NULL, NULL, NULL,
    'Банкетный зал',
    'Banquet Hall',
    'Толори банкет',
    4
),
(
    (SELECT id FROM program_days WHERE day_number = 3),
    'session',
    '14:30', '17:00',
    'Специальные мероприятия партнёров',
    'Partner Special Events',
    'Чорабиниҳои махсуси шарикон',
    'Параллельные сессии международных организаций',
    'Parallel sessions by international organizations',
    'Сессияҳои параллелии ташкилотҳои байналмилалӣ',
    'Залы A, B, C',
    'Halls A, B, C',
    'Толорҳои A, B, C',
    5
);

-- ============================================
-- PROGRAM EVENTS - DAY 4
-- ============================================

INSERT OR IGNORE INTO program_events (day_id, event_type, time_start, time_end, title_ru, title_en, title_tj, description_ru, description_en, description_tj, location_ru, location_en, location_tj, sort_order) VALUES
(
    (SELECT id FROM program_days WHERE day_number = 4),
    'plenary',
    '09:00', '10:30',
    'Подготовка итоговых документов',
    'Final Documents Preparation',
    'Тайёр кардани ҳуҷҷатҳои ниҳоӣ',
    'Финализация декларации конференции',
    'Finalization of conference declaration',
    'Ниҳоӣ кардани эъломияи конфронс',
    'Зал заседаний',
    'Meeting Room',
    'Толори ҷаласа',
    1
),
(
    (SELECT id FROM program_days WHERE day_number = 4),
    'break',
    '10:30', '11:00',
    'Кофе-брейк',
    'Coffee Break',
    'Танаффуси қаҳва',
    NULL, NULL, NULL,
    'Фойе',
    'Foyer',
    'Фойе',
    2
),
(
    (SELECT id FROM program_days WHERE day_number = 4),
    'plenary',
    '11:00', '12:30',
    'Принятие итоговых документов',
    'Adoption of Final Documents',
    'Қабули ҳуҷҷатҳои ниҳоӣ',
    'Официальное принятие Душанбинской декларации',
    'Official adoption of the Dushanbe Declaration',
    'Қабули расмии Эъломияи Душанбе',
    'Главный зал',
    'Main Hall',
    'Толори асосӣ',
    3
),
(
    (SELECT id FROM program_days WHERE day_number = 4),
    'ceremony',
    '12:30', '13:30',
    'Торжественная церемония закрытия',
    'Grand Closing Ceremony',
    'Маросими тантанавии хотима',
    'Подведение итогов и закрытие конференции',
    'Summary and closing of the conference',
    'Ҷамъбаст ва хотимаи конфронс',
    'Главный зал',
    'Main Hall',
    'Толори асосӣ',
    4
),
(
    (SELECT id FROM program_days WHERE day_number = 4),
    'break',
    '13:30', '15:00',
    'Торжественный обед',
    'Gala Lunch',
    'Хӯроки тантанавӣ',
    NULL, NULL, NULL,
    'Банкетный зал',
    'Banquet Hall',
    'Толори банкет',
    5
);

-- ============================================
-- COUNTRIES DATA (with multilingual names)
-- ============================================

INSERT OR IGNORE INTO countries (code, name_ru, name_en, name_tj, sort_order) VALUES
('TJ', 'Таджикистан', 'Tajikistan', 'Тоҷикистон', 0),
('AF', 'Афганистан', 'Afghanistan', 'Афғонистон', 1),
('AL', 'Албания', 'Albania', 'Албания', 2),
('DZ', 'Алжир', 'Algeria', 'Алҷазоир', 3),
('AD', 'Андорра', 'Andorra', 'Андорра', 4),
('AO', 'Ангола', 'Angola', 'Ангола', 5),
('AG', 'Антигуа и Барбуда', 'Antigua and Barbuda', 'Антигуа ва Барбуда', 6),
('AR', 'Аргентина', 'Argentina', 'Аргентина', 7),
('AM', 'Армения', 'Armenia', 'Арманистон', 8),
('AU', 'Австралия', 'Australia', 'Австралия', 9),
('AT', 'Австрия', 'Austria', 'Австрия', 10),
('AZ', 'Азербайджан', 'Azerbaijan', 'Озарбойҷон', 11),
('BS', 'Багамы', 'Bahamas', 'Баҳама', 12),
('BH', 'Бахрейн', 'Bahrain', 'Баҳрайн', 13),
('BD', 'Бангладеш', 'Bangladesh', 'Бангладеш', 14),
('BB', 'Барбадос', 'Barbados', 'Барбадос', 15),
('BY', 'Беларусь', 'Belarus', 'Беларус', 16),
('BE', 'Бельгия', 'Belgium', 'Белгия', 17),
('BZ', 'Белиз', 'Belize', 'Белиз', 18),
('BJ', 'Бенин', 'Benin', 'Бенин', 19),
('BT', 'Бутан', 'Bhutan', 'Бутон', 20),
('BO', 'Боливия', 'Bolivia', 'Боливия', 21),
('BA', 'Босния и Герцеговина', 'Bosnia and Herzegovina', 'Босния ва Ҳерсеговина', 22),
('BW', 'Ботсвана', 'Botswana', 'Ботсвана', 23),
('BR', 'Бразилия', 'Brazil', 'Бразилия', 24),
('BN', 'Бруней', 'Brunei', 'Бруней', 25),
('BG', 'Болгария', 'Bulgaria', 'Булғористон', 26),
('BF', 'Буркина-Фасо', 'Burkina Faso', 'Буркина-Фасо', 27),
('BI', 'Бурунди', 'Burundi', 'Бурунди', 28),
('CV', 'Кабо-Верде', 'Cape Verde', 'Кабо-Верде', 29),
('KH', 'Камбоджа', 'Cambodia', 'Камбоҷа', 30),
('CM', 'Камерун', 'Cameroon', 'Камерун', 31),
('CA', 'Канада', 'Canada', 'Канада', 32),
('CF', 'Центральноафриканская Республика', 'Central African Republic', 'Ҷумҳурии Африқои Марказӣ', 33),
('TD', 'Чад', 'Chad', 'Чад', 34),
('CL', 'Чили', 'Chile', 'Чили', 35),
('CN', 'Китай', 'China', 'Хитой', 36),
('CO', 'Колумбия', 'Colombia', 'Колумбия', 37),
('KM', 'Коморы', 'Comoros', 'Комор', 38),
('CG', 'Конго', 'Congo', 'Конго', 39),
('CD', 'Демократическая Республика Конго', 'Democratic Republic of the Congo', 'Ҷумҳурии Демократии Конго', 40),
('CR', 'Коста-Рика', 'Costa Rica', 'Коста-Рика', 41),
('HR', 'Хорватия', 'Croatia', 'Хорватия', 42),
('CU', 'Куба', 'Cuba', 'Куба', 43),
('CY', 'Кипр', 'Cyprus', 'Кипр', 44),
('CZ', 'Чехия', 'Czech Republic', 'Чехия', 45),
('DK', 'Дания', 'Denmark', 'Дания', 46),
('DJ', 'Джибути', 'Djibouti', 'Ҷибути', 47),
('DM', 'Доминика', 'Dominica', 'Доминика', 48),
('DO', 'Доминиканская Республика', 'Dominican Republic', 'Ҷумҳурии Доминикан', 49),
('EC', 'Эквадор', 'Ecuador', 'Эквадор', 50),
('EG', 'Египет', 'Egypt', 'Миср', 51),
('SV', 'Сальвадор', 'El Salvador', 'Эл-Салвадор', 52),
('GQ', 'Экваториальная Гвинея', 'Equatorial Guinea', 'Гвинеяи Экваториалӣ', 53),
('ER', 'Эритрея', 'Eritrea', 'Эритрея', 54),
('EE', 'Эстония', 'Estonia', 'Эстония', 55),
('SZ', 'Эсватини', 'Eswatini', 'Эсватини', 56),
('ET', 'Эфиопия', 'Ethiopia', 'Эфиопия', 57),
('FJ', 'Фиджи', 'Fiji', 'Фиҷӣ', 58),
('FI', 'Финляндия', 'Finland', 'Финландия', 59),
('FR', 'Франция', 'France', 'Фаронса', 60),
('GA', 'Габон', 'Gabon', 'Габон', 61),
('GM', 'Гамбия', 'Gambia', 'Гамбия', 62),
('GE', 'Грузия', 'Georgia', 'Гурҷистон', 63),
('DE', 'Германия', 'Germany', 'Олмон', 64),
('GH', 'Гана', 'Ghana', 'Гана', 65),
('GR', 'Греция', 'Greece', 'Юнон', 66),
('GD', 'Гренада', 'Grenada', 'Гренада', 67),
('GT', 'Гватемала', 'Guatemala', 'Гватемала', 68),
('GN', 'Гвинея', 'Guinea', 'Гвинея', 69),
('GW', 'Гвинея-Бисау', 'Guinea-Bissau', 'Гвинея-Бисау', 70),
('GY', 'Гайана', 'Guyana', 'Гайана', 71),
('HT', 'Гаити', 'Haiti', 'Ҳаити', 72),
('HN', 'Гондурас', 'Honduras', 'Ҳондурас', 73),
('HU', 'Венгрия', 'Hungary', 'Маҷористон', 74),
('IS', 'Исландия', 'Iceland', 'Исландия', 75),
('IN', 'Индия', 'India', 'Ҳиндустон', 76),
('ID', 'Индонезия', 'Indonesia', 'Индонезия', 77),
('IR', 'Иран', 'Iran', 'Эрон', 78),
('IQ', 'Ирак', 'Iraq', 'Ироқ', 79),
('IE', 'Ирландия', 'Ireland', 'Ирландия', 80),
('IL', 'Израиль', 'Israel', 'Исроил', 81),
('IT', 'Италия', 'Italy', 'Италия', 82),
('JM', 'Ямайка', 'Jamaica', 'Ямайка', 83),
('JP', 'Япония', 'Japan', 'Ҷопон', 84),
('JO', 'Иордания', 'Jordan', 'Урдун', 85),
('KZ', 'Казахстан', 'Kazakhstan', 'Қазоқистон', 86),
('KE', 'Кения', 'Kenya', 'Кения', 87),
('KI', 'Кирибати', 'Kiribati', 'Кирибати', 88),
('KP', 'Северная Корея', 'North Korea', 'Кореяи Шимолӣ', 89),
('KR', 'Южная Корея', 'South Korea', 'Кореяи Ҷанубӣ', 90),
('KW', 'Кувейт', 'Kuwait', 'Қувайт', 91),
('KG', 'Кыргызстан', 'Kyrgyzstan', 'Қирғизистон', 92),
('LA', 'Лаос', 'Laos', 'Лаос', 93),
('LV', 'Латвия', 'Latvia', 'Латвия', 94),
('LB', 'Ливан', 'Lebanon', 'Лубнон', 95),
('LS', 'Лесото', 'Lesotho', 'Лесото', 96),
('LR', 'Либерия', 'Liberia', 'Либерия', 97),
('LY', 'Ливия', 'Libya', 'Либия', 98),
('LI', 'Лихтенштейн', 'Liechtenstein', 'Лихтенштейн', 99),
('LT', 'Литва', 'Lithuania', 'Литва', 100),
('LU', 'Люксембург', 'Luxembourg', 'Люксембург', 101),
('MG', 'Мадагаскар', 'Madagascar', 'Мадагаскар', 102),
('MW', 'Малави', 'Malawi', 'Малави', 103),
('MY', 'Малайзия', 'Malaysia', 'Малайзия', 104),
('MV', 'Мальдивы', 'Maldives', 'Малдив', 105),
('ML', 'Мали', 'Mali', 'Мали', 106),
('MT', 'Мальта', 'Malta', 'Малта', 107),
('MH', 'Маршалловы Острова', 'Marshall Islands', 'Ҷазираҳои Маршалл', 108),
('MR', 'Мавритания', 'Mauritania', 'Мавритания', 109),
('MU', 'Маврикий', 'Mauritius', 'Маврикий', 110),
('MX', 'Мексика', 'Mexico', 'Мексика', 111),
('FM', 'Микронезия', 'Micronesia', 'Микронезия', 112),
('MD', 'Молдова', 'Moldova', 'Молдова', 113),
('MC', 'Монако', 'Monaco', 'Монако', 114),
('MN', 'Монголия', 'Mongolia', 'Муғулистон', 115),
('ME', 'Черногория', 'Montenegro', 'Черногория', 116),
('MA', 'Марокко', 'Morocco', 'Марокаш', 117),
('MZ', 'Мозамбик', 'Mozambique', 'Мозамбик', 118),
('MM', 'Мьянма', 'Myanmar', 'Мянма', 119),
('NA', 'Намибия', 'Namibia', 'Намибия', 120),
('NR', 'Науру', 'Nauru', 'Науру', 121),
('NP', 'Непал', 'Nepal', 'Непал', 122),
('NL', 'Нидерланды', 'Netherlands', 'Нидерландия', 123),
('NZ', 'Новая Зеландия', 'New Zealand', 'Зеландияи Нав', 124),
('NI', 'Никарагуа', 'Nicaragua', 'Никарагуа', 125),
('NE', 'Нигер', 'Niger', 'Нигер', 126),
('NG', 'Нигерия', 'Nigeria', 'Нигерия', 127),
('MK', 'Северная Македония', 'North Macedonia', 'Македонияи Шимолӣ', 128),
('NO', 'Норвегия', 'Norway', 'Норвегия', 129),
('OM', 'Оман', 'Oman', 'Умон', 130),
('PK', 'Пакистан', 'Pakistan', 'Покистон', 131),
('PW', 'Палау', 'Palau', 'Палау', 132),
('PS', 'Палестина', 'Palestine', 'Фаластин', 133),
('PA', 'Панама', 'Panama', 'Панама', 134),
('PG', 'Папуа — Новая Гвинея', 'Papua New Guinea', 'Папуа-Гвинеяи Нав', 135),
('PY', 'Парагвай', 'Paraguay', 'Парагвай', 136),
('PE', 'Перу', 'Peru', 'Перу', 137),
('PH', 'Филиппины', 'Philippines', 'Филиппин', 138),
('PL', 'Польша', 'Poland', 'Полша', 139),
('PT', 'Португалия', 'Portugal', 'Португалия', 140),
('QA', 'Катар', 'Qatar', 'Қатар', 141),
('RO', 'Румыния', 'Romania', 'Руминия', 142),
('RU', 'Россия', 'Russia', 'Русия', 143),
('RW', 'Руанда', 'Rwanda', 'Руанда', 144),
('KN', 'Сент-Китс и Невис', 'Saint Kitts and Nevis', 'Сент-Китс ва Невис', 145),
('LC', 'Сент-Люсия', 'Saint Lucia', 'Сент-Люсия', 146),
('VC', 'Сент-Винсент и Гренадины', 'Saint Vincent and the Grenadines', 'Сент-Винсент ва Гренадинҳо', 147),
('WS', 'Самоа', 'Samoa', 'Самоа', 148),
('SM', 'Сан-Марино', 'San Marino', 'Сан-Марино', 149),
('ST', 'Сан-Томе и Принсипи', 'Sao Tome and Principe', 'Сан-Томе ва Принсипи', 150),
('SA', 'Саудовская Аравия', 'Saudi Arabia', 'Арабистони Саудӣ', 151),
('SN', 'Сенегал', 'Senegal', 'Сенегал', 152),
('RS', 'Сербия', 'Serbia', 'Сербия', 153),
('SC', 'Сейшелы', 'Seychelles', 'Сейшел', 154),
('SL', 'Сьерра-Леоне', 'Sierra Leone', 'Сиерра-Леоне', 155),
('SG', 'Сингапур', 'Singapore', 'Сингапур', 156),
('SK', 'Словакия', 'Slovakia', 'Словакия', 157),
('SI', 'Словения', 'Slovenia', 'Словения', 158),
('SB', 'Соломоновы Острова', 'Solomon Islands', 'Ҷазираҳои Соломон', 159),
('SO', 'Сомали', 'Somalia', 'Сомалӣ', 160),
('ZA', 'Южная Африка', 'South Africa', 'Африқои Ҷанубӣ', 161),
('SS', 'Южный Судан', 'South Sudan', 'Судони Ҷанубӣ', 162),
('ES', 'Испания', 'Spain', 'Испания', 163),
('LK', 'Шри-Ланка', 'Sri Lanka', 'Шри-Ланка', 164),
('SD', 'Судан', 'Sudan', 'Судон', 165),
('SR', 'Суринам', 'Suriname', 'Суринам', 166),
('SE', 'Швеция', 'Sweden', 'Шветсия', 167),
('CH', 'Швейцария', 'Switzerland', 'Швейтсария', 168),
('SY', 'Сирия', 'Syria', 'Сурия', 169),
('TZ', 'Танзания', 'Tanzania', 'Танзания', 170),
('TH', 'Таиланд', 'Thailand', 'Тайланд', 171),
('TL', 'Восточный Тимор', 'Timor-Leste', 'Тимори Шарқӣ', 172),
('TG', 'Того', 'Togo', 'Того', 173),
('TO', 'Тонга', 'Tonga', 'Тонга', 174),
('TT', 'Тринидад и Тобаго', 'Trinidad and Tobago', 'Тринидад ва Тобаго', 175),
('TN', 'Тунис', 'Tunisia', 'Тунис', 176),
('TR', 'Турция', 'Turkey', 'Туркия', 177),
('TM', 'Туркменистан', 'Turkmenistan', 'Туркманистон', 178),
('TV', 'Тувалу', 'Tuvalu', 'Тувалу', 179),
('UG', 'Уганда', 'Uganda', 'Уганда', 180),
('UA', 'Украина', 'Ukraine', 'Украина', 181),
('AE', 'ОАЭ', 'United Arab Emirates', 'Аморати Муттаҳидаи Араб', 182),
('GB', 'Великобритания', 'United Kingdom', 'Британияи Кабир', 183),
('US', 'США', 'United States', 'ИМА', 184),
('UY', 'Уругвай', 'Uruguay', 'Уругвай', 185),
('UZ', 'Узбекистан', 'Uzbekistan', 'Ӯзбекистон', 186),
('VU', 'Вануату', 'Vanuatu', 'Вануату', 187),
('VA', 'Ватикан', 'Vatican City', 'Ватикан', 188),
('VE', 'Венесуэла', 'Venezuela', 'Венесуэла', 189),
('VN', 'Вьетнам', 'Vietnam', 'Вьетнам', 190),
('YE', 'Йемен', 'Yemen', 'Яман', 191),
('ZM', 'Замбия', 'Zambia', 'Замбия', 192),
('ZW', 'Зимбабве', 'Zimbabwe', 'Зимбабве', 193);
